gulp = require('gulp')
jetpack = require('fs-jetpack')
bundle = require('./bundle')
istanbul = require('rollup-plugin-istanbul')

# Spec files are scattered through the whole project. Here we're searching
# for them and generate one entry file which will run all the tests.

generateEntryFile = (dir, destFileName, filePattern) =>
  fileBanner = '// This file is generated automatically.\n' + '// All modifications will be lost.\n'
  dir.findAsync('.', matching: filePattern).then((specPaths) =>
    fileContent = specPaths.map((path) ->
      'import "./' + path.replace(/\\/g, '/') + '";'
    ).join('\n')
    dir.writeAsync destFileName, fileBanner + fileContent
  ).then =>
    dir.path destFileName


gulp.task 'build-unit', [ 'environment' ], =>
  srcDir = jetpack.cwd('src')
  destDir = jetpack.cwd('app')
  generateEntryFile(srcDir, 'specs.js.autogenerated', '*.spec.js').then (entryFilePath) =>
    bundle entryFilePath, destDir.path('specs.js.autogenerated'), rollupPlugins: [ istanbul(
      exclude: [
        '**/*.spec.js'
        '**/specs.js.autogenerated'
      ]
      sourceMap: true) ]


gulp.task 'build-e2e', [ 'build' ], =>
  srcDir = jetpack.cwd('e2e')
  destDir = jetpack.cwd('app')
  generateEntryFile(srcDir, 'e2e.js.autogenerated', '*.e2e.js').then (entryFilePath) =>
    bundle entryFilePath, destDir.path('e2e.js.autogenerated')
